@startuml state_machine_with_collision
<style>
stateDiagram {
  FontSize 24
  arrow {
    FontSize 18
  }
}
</style>

[*] --> OPERATIONAL

state OPERATIONAL {
[*]--> NO_DEST

NO_DEST --> COLLISION_NO_DEST: T11/L_TURN
NO_DEST --> COLLISION_TURN_LEFT: T12/L_TURN\n\n
NO_DEST --> COLLISION_TURN_RIGHT: T13/L_TURN\n\n
NO_DEST --> COLLISION_PASS: \n\nT14/L_TURN
NO_DEST --> COLLISION_DOCK: \n\nT15/L_TURN

SHOULD_TURN_LEFT --> COLLISION_TURN_LEFT: T11||T12||T13||\nT14||T15/L_TURN

SHOULD_TURN_RIGHT --> COLLISION_TURN_RIGHT: T11||T12||T13||\nT14||T15/L_TURN

SHOULD_PASS --> COLLISION_PASS: T11||T12||T13||\nT14||T15/L_TURN

SHOULD_DOCK --> COLLISION_DOCK: T11||T12||T13||\nT14||T15/L_TURN

COLLISION_NO_DEST --> COLLISION_NO_DEST: T11/L_TURN
COLLISION_NO_DEST --> COLLISION_TURN_LEFT: T12/L_TURN\n\n
COLLISION_NO_DEST --> COLLISION_TURN_RIGHT: T13/L_TURN\n\n
COLLISION_NO_DEST --> COLLISION_PASS: \n\nT14/L_TURN
COLLISION_NO_DEST --> COLLISION_DOCK: \n\nT15/L_TURN

COLLISION_TURN_LEFT --> COLLISION_TURN_LEFT: T11||T12||T13||\nT14||T15/L_TURN

COLLISION_TURN_RIGHT --> COLLISION_TURN_RIGHT: T11||T12||T13||\nT14||T15/L_TURN

COLLISION_PASS --> COLLISION_PASS: \nT11||T12||T13||\nT14||T15/L_TURN

COLLISION_DOCK --> COLLISION_DOCK: T11||T12||T13||\nT14||T15/L_TURN

HANDLE_INTERSECTION --> COLLISION_INTERSECTION: T11||T12||T13||\nT14||T15/L_TURN

COLLISION_INTERSECTION --> COLLISION_INTERSECTION: T11||T12||T13||\nT14||T15/L_TURN
}
@enduml