@startuml state_machine_with_collision
<style>
stateDiagram {
  FontSize 24
  arrow {
    FontSize 18
  }
}
</style>

[*] --> OPERATIONAL

state OPERATIONAL {
[*]--> NO_DEST

NO_DEST --> COLLISION_NO_DEST: T13/L_TURN
NO_DEST --> COLLISION_TURN_LEFT: T14/L_TURN\n\n
NO_DEST --> COLLISION_TURN_RIGHT: T15/L_TURN\n\n
NO_DEST --> COLLISION_PASS: \n\nT16/L_TURN
NO_DEST --> COLLISION_U_TURN: \n\nT17/L_TURN
NO_DEST --> COLLISION_DOCK: \n\nT18/L_TURN

SHOULD_TURN_LEFT --> COLLISION_TURN_LEFT: T13||T14||T15||\nT16||T17||T18/L_TURN

SHOULD_TURN_RIGHT --> COLLISION_TURN_RIGHT: T13||T14||T15||\nT16||T17||T18/L_TURN

SHOULD_PASS --> COLLISION_PASS: T13||T14||T15||\nT16||T17||T18/L_TURN

SHOULD_U_TURN --> COLLISION_U_TURN: T13||T14||T15||\nT16||T17||T18/L_TURN

SHOULD_DOCK --> COLLISION_DOCK: T13||T14||T15||\nT16||T17||T18/L_TURN

HANDLE_INTERSECTION --> COLLISION_INTERSECTION: TT13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_NO_DEST --> COLLISION_NO_DEST: T13/L_TURN
COLLISION_NO_DEST --> COLLISION_TURN_LEFT: T14/L_TURN\n\n
COLLISION_NO_DEST --> COLLISION_TURN_RIGHT: T15/L_TURN\n\n
COLLISION_NO_DEST --> COLLISION_PASS: \n\nT16/L_TURN
COLLISION_NO_DEST --> COLLISION_U_TURN: \n\nT17/L_TURN
COLLISION_NO_DEST --> COLLISION_DOCK: \n\nT18/L_TURN

COLLISION_TURN_LEFT --> COLLISION_TURN_LEFT: T13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_TURN_RIGHT --> COLLISION_TURN_RIGHT: T13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_PASS --> COLLISION_PASS: \nT13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_U_TURN --> COLLISION_U_TURN: T13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_DOCK --> COLLISION_DOCK: T13||T14||T15||\nT16||T17||T18/L_TURN

COLLISION_INTERSECTION --> COLLISION_INTERSECTION: T13||T14||T15||\nT16||T17||T18/L_TURN
}
@enduml