@startuml
User <|-- Superuser



rectangle Mail<U+0020>Delivery<U+0020>Service<U+0020>Robot:<U+0020>Web<U+0020>Application {
    left to right direction
    together {
    usecase RegisterAccount
    usecase LoginAccount
    usecase LogoutAccount
    }
    together {
        usecase CreateDelivery
        usecase ViewStatus
        usecase UpdateStatus
    }
    together {
        usecase ManageRobots
        usecase AddRobots
        usecase RegisterAdmin
        usecase RemoveUser
    }
    
    RegisterAccount <-- LoginAccount: <<include>>
    CreateDelivery --> LoginAccount: <<include>>
    CreateDelivery <-- ViewStatus: <<include>>
    ViewStatus <-- UpdateStatus: <<include>>
    LoginAccount <-- LogoutAccount: <<include>>
    ManageRobots <-- AddRobots: <<extends>>


}
actor Robot
actor Authentication

User -- RegisterAccount
User -- CreateDelivery
Authentication -- LoginAccount
Superuser -- ManageRobots
Superuser -- RegisterAdmin
Superuser -- RemoveUser
Robot -- UpdateStatus
@enduml