name: ROS Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          colcon build --packages-select mail_delivery_robot --symlink-install

      - name: Run tests
        run: |
          colcon test --packages-select mail_delivery_robot --event-handlers console_cohesion+