name: ROS Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        ros-distro: humble

    - name: build and test
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: mail_delivery_robot
        target-ros2-distro: humble
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
          }
        # If possible, pin the repository in the workflow to a specific commit to avoid
        # changes in colcon-mixin-repository from breaking your tests.
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml

